### ISSUE TITLE
Feedback from first course delivery of lesson 1

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/grad_school_git_course#11]
# Instructor/Helper Feedback
* Getting the example project downloaded and ready to use was time consuming - some optimisation would be useful here
* Had to slightly rush the section on merging at the end
* There is scope for additional material in the notes for people to study in their own time.

# Positive Attendee Feedback
* Good pace
* The pace of the lecture is very good
* Pace was good, not too fast
* Good pace not too fast
* The step-by-step notes are really helpful
* Pictorial representation for explaining branches was good
* Instructions are clear
* Easy to follow
* Easy to handle examples
* Structure of the course was good
* Structured well
* Useful to see git concepts illustrated with simple example
* Useful to have git jargon explained rather than having it assumed to be obvious
* I found very useful and clear the way in which the course was held
* Detailed explanation
* Course material is quite clear!
* Easy to understand
* I really like the online notes, they are super helpful
* Quite easy to follow in the command line
* Good to have the live coding and examples
* Good handouts with easily readable info and detailed explanations
* Having the instructions on the website is quite useful
* Reliable help
* Support was prompt and helpful also
* Instant help on queries
* Clear explanation both written and oral

# Negative Attendee Feedback
* More basic introduction/preparation
* More examples as a take away for some hands-on
* Could provide exercises solution after time given to solve them so that everybody is on the same page
* Maybe show more git commands and/or provide documentation
* Sometimes the pace is a little fast
* Feels a bit rushed towards the end of merging
* The pace was quite slow
* So far very good! No bad points.
* Typos
* Nothing springs to mind
* None
* Room hard to find, got lost

Any other feedback @dalonsoa, @tonyyzy?

**Comment by tonyyzy** [comment]
- The pace was good, can type a tad bit slower
- Need to remind and get everyone used to using post-its
- Very clear explanation and high familiarity with the material
- The bottom of the screen was hard to see at the beginning but fixed promptly
- Maybe a quick mention of code of conduct at the start?
