### ISSUE TITLE
Instructions to join GitHub

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/grad_school_git_course#19]
Instructions to join GitHub are missing fro the [setup](https://imperialcollegelondon.github.io/grad_school_git_course/setup.html). Probably lost in an update at some point.

**Comment by dandavies99** [comment]
These were lost in [this commit](https://github.com/ImperialCollegeLondon/grad_school_git_course/commit/dd39d85240c67b45f0bdaf358ccea6b57afb5e20#diff-8101172204c38bd6b3e15b1bccc0e8d9e1d2ebf5b89c8e25714ac7d8f7c7c426) when moving to remote delivery. I suggest adding the instructions back in to the section [_Github: Why Github?_](https://imperialcollegelondon.github.io/grad_school_git_course/l2-01-sharing_your_code/index.html) in lesson 4 instead - seems like the most sensible place. This is related to #22 so I'll make some changes including instructions for creating a PAT.
